package:
  name: hydrogen
  version: "0.0.1"

source:
  git_tag: master
  git_url: https://github.com/yowtzu/hydrogen

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
    - nose

  run:
    - python
    - numpy
    - pandas
    - nose

  # Python imports
  #imports:
  #  - pyinstrument

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/yowtzu/hydrogen
  license: BSD License
  summary: "Hydrogen: Let there be money"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
