system:
  trading_capital: 1000000
  vol_target_pct: 0.2 # see page 147 for setting

  n_day_in_year: 365
  n_bday_in_year: 256
  n_month_in_year: 12
  n_week_in_year: 52

  epoch: 2005-01-01
  avg_abs_forecast: 10.0